//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_Colectiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int idMedic { get; set; }
        public string cardNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> idmedicalPrescription { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Medic Medic { get; set; }
        public virtual medicalPrescription medicalPrescription { get; set; }
    }
}
