//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_Colectiv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
        }

        [Key]
        public string cardNumber { get; set; }
     
        public string firstName { get; set; }
        
        public string lastName { get; set; }
       
        public System.DateTime birthDate { get; set; }
        
        public string email { get; set; }
        public Nullable<int> idMedic { get; set; }
       
        public string CNP { get; set; }
        public Nullable<int> idmedicalRecords { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Medic Medic { get; set; }
        public virtual medicalRecord medicalRecord { get; set; }
    }
}
